name: BananaCamera
version: '${project.version}'
main: cbejl.bananacamera.BananaCamera
api-version: '1.20'
commands:
  bcamera:
    permission: "bcamera.control"
permissions:
  bcamera.control:
    description: "control server camera"